
  export const categories = [
    {
      id: 1,
      img: "https://i1.adis.ws/i/boohooamplience/bmm10014_charcoal_xl/charcoal-oversized-flame-print-acid-wash-t-shirt?$product_page_main_magic_zoom$",
      title: "SHIRTS",
    },
    {
      id: 2,
      img: "https://i1.adis.ws/i/boohooamplience/bmm12827_light%20blue_xl/light-blue-relaxed-fit-busted-knee-jeans?$product_page_main_magic_zoom$",
      title: "JEANS",
    },
    {
      id: 3,
      img: "https://i1.adis.ws/i/boohooamplience/bmm11190_black_xl/black-man-raglan-tape-hoodie?$product_page_main_magic_zoom$",
      title: "HOODIES",
    },
  ];

  export const popularProducts = [
    {
      id:1,
      img:"https://i.ibb.co/TKYfG7Q/black-tall-palm-embroidered-oversized-hoodie-removebg-preview.png",
      color: "Black",
      size: "M",
      gender: "Men",
      condition: "New",
      price: 26,
      name: "Black Tree Hoodie",
    },
    {
      id:2,
      img:"https://i.ibb.co/p2QpzHg/grey-relaxed-fit-over-dye-jean-removebg-preview.png",
      color: "Black",
      size: "L",
      gender: "Men",
      condition: "New",
      price: 30,
      name: "Black Jeans",
    },
    {
      id:3,
      img:"https://i.ibb.co/rm4hV3T/charcoal-oversized-bleach-tie-dye-graphic-t-shirt-removebg-preview.png",
      color: "White",
      size: "S",
      gender: "Men",
      condition: "New",
      price: 12,
      name: "White Los Angels T-Shirt",
    },
    {
      id:4,
      img:"https://i.ibb.co/wz6684D/mid-blue-relaxed-fit-rigid-jeans-removebg-preview-1.png",
      color: "Blue",
      size: "S",
      gender: "Men",
      condition: "Used",
      price: 28,
      name: "Classic Jeans",
    },
    {
      id:5,
      img:"https://i.ibb.co/Zmz0mCQ/orange-regular-fit-back-graphic-t-shirt-removebg-preview.png",
      color: "Orange",
      size: "L",
      gender: "Men",
      condition: "New",
      price: 12,
      name: "Orange Dragon T-Shirt",
    },
    {
      id:6,
      img:"https://i.ibb.co/mtYwnZ7/white-relaxed-fit-rigid-jeans-removebg-preview.png",
      color: "White",
      size: "M",
      gender: "Men",
      condition: "New",
      price: 25,
      name: "White Jeans",
    },
    {
      id:7,
      img:"https://i.ibb.co/mRDbtSj/khaki-straight-leg-twill-cargo-trousers-removebg-preview.png",
      color: "Green",
      size: "L",
      gender: "Men",
      condition: "Used",
      price: 18,
      name: "Green Cargo Pants",
    },
    {
      id:8,
      img:"https://i.ibb.co/qy5T4Td/charcoal-oversized-worldwide-dove-acid-wash-t-shirt-removebg-preview.png",
      color: "Blue",
      size: "M",
      gender: "Men",
      condition: "Used",
      price: 14,
      name: "Blue Marine T-Shirt",
    },
    {
      id:9,
      img:"https://i.ibb.co/G2QqcNC/light-blue-oversized-denim-jacket-removebg-preview.png",
      color: "Blue",
      size: "M",
      gender: "Men",
      condition: "New",
      price: 30,
      name: "Denim Jacket",
    },
    {
      id:10,
      img:"https://i.ibb.co/87bQn9p/TUVMY-SQ1-0000000047-GREEN-MDf-removebg-preview.png",
      color: "Green",
      size: "M",
      gender: "Women",
      condition: "New",
      price: 30,
      name: "Green Dress",
    },
    {
      id:11,
      img:"https://i.ibb.co/2FTKSgN/TUV9-J-SQ1-0000000198-ORANGE-MDf-removebg-preview.png",
      color: "Orange",
      size: "S",
      gender: "Women",
      condition: "New",
      price: 42,
      name: "Orange Dress",
    },
    {
      id:12,
      img:"https://i.ibb.co/k9zhtML/TLCQN-SQ1-0000000004-BLACK-MDf-removebg-preview.png",
      color: "Black",
      size: "M",
      gender: "Women",
      condition: "Used",
      price: 17,
      name: "Black Legging",
    },
    {
      id:13,
      img:"https://i.ibb.co/QC4jTcZ/UC4-MJ-SQ3-0000000013-WHITE-MDo-removebg-preview.png",
      color: "White",
      size: "S",
      gender: "Women",
      condition: "New",
      price: 25,
      name: "White Dress",
    },
    {
      id:14,
      img:"https://i.ibb.co/t895FNF/UJJHA-SQ1-0000000220-GREEN-PRINT-MDf-removebg-preview.png",
      color: "Green",
      size: "XL",
      gender: "Women",
      condition: "New",
      price: 50,
      name: "Green Dress",
    },
    {
      id:15,
      img:"https://i.ibb.co/x2rpZW8/UJ3-HQ-SQ1-0000000019-BLACK-WHITE-MDf-removebg-preview.png",
      color: "Black",
      size: "M",
      gender: "Women",
      condition: "Used",
      price: 32,
      name: "Black Sports Coat",
    },
  ]
  export const sellingProducts = [
    {
      id:1,
      img:"https://images1.vinted.net/t/01_01f56_NcFy3VzbZ1wsGfkCMFuT7tzY/f800/1652806120.jpeg?s=47d63ca1026fe87fbcd6f3dc4abcf283caa5910a",
    },
    {
      id:2,
      img:"https://images1.vinted.net/t/01_009db_r9e2cHpEfZVT6JZbQd3k7skT/f800/1652031525.jpeg?s=2e62966168a956ca298412bf3ad3d73e63d65727",
    },
    {
      id:3,
      img:"https://images1.vinted.net/t/03_00413_6JJjzBvcBGveGvW11VPhi2yb/f800/1652965943.jpeg?s=5e81d00f90da826a9ea2647c6da35d210cf854f4",
    },

    
  ]